extension_dir = "C:\Users\jimis\AppData\Roaming\Local\lightning-services\php-8.3.29+1\bin\win64\ext"
extension = php_openssl.dll
extension = php_curl.dll
extension = php_mbstring.dll
extension = php_pdo_mysql.dll
extension = php_pdo_pgsql.dll
extension = php_mysqli.dll
extension = php_zip.dll
